version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: teleo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
